name: orado_customer
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.1
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.16
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  google_places_flutter: ^2.1.0
  intl: ^0.20.1
  loading_animation_widget: ^1.3.0
  location: ^7.0.1
  lottie: ^3.3.1
  ola_maps: ^0.0.2
  permission_handler: ^11.3.1
  provider: ^6.1.2
  razorpay_flutter: ^1.3.7
  shared_preferences: ^2.3.4
  shimmer: ^3.0.0
  socket_io_client: ^3.1.2
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  image_path: "assets/images/logo_edit.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/map_style.json
    - assets/animations/
    - assets/animations/Dlivery Map.json

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/Raleway/static/Raleway-Regular.ttf
          weight: 400
        - asset: assets/Raleway/static/Raleway-Bold.ttf
          weight: 700
        - asset: assets/Raleway/static/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/Raleway/static/Raleway-Medium.ttf
          weight: 500
        - asset: assets/Raleway/static/Raleway-Light.ttf
          weight: 300
        - asset: assets/Raleway/static/Raleway-ExtraBold.ttf
          weight: 800
    - family: OradoIcon
      fonts:
        - asset: assets/OradoIcon.ttf
