/// Flutter icons OradoIcon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OradoIcon
///      fonts:
///       - asset: fonts/OradoIcon.ttf
///
///
///
// ignore_for_file: avoid_redundant_argument_values

import 'package:flutter/widgets.dart';

class OradoIcon {
  OradoIcon._();

  static const String _kFontFam = 'OradoIcon';
  static const String? _kFontPkg = null;

  static const IconData star_outlined = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_coloured = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_coloured = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_1 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favourites_coloured = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orders_outlined = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_outlined = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData offer = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_outlined = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favourites = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orders = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_coloured = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_pin = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_2 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_coloured = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
